version: "2.4"
services:
  kaggle-jupyter:
    container_name: 'kaggle-jupyter'
    build: ..
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - $PWD:/home
      - $PWD/share:/opt/conda/share/jupyter/lab
    working_dir: /home
    ports:
      - 9876:8080
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser
