version: "2.4"
services:
  kaggle-jupyter:
    container_name: 'kaggle-jupyter'
    build: ..
    runtime: nvidia
    volumes:
      - $PWD:/mount
    working_dir: /mount
    ports:
      - 9876:8080
    command: jupyter notebook --ip=0.0.0.0 --allow-root --no-browser
