version: "2.4"
services:
  kaggle-jupyter:
    container_name: 'kaggle-jupyter'
    image: 'okojoalg/kaggle-gpu:v0.2-36'
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - $PWD:/home
    working_dir: /home
    ports:
      - 9876:8080
    command: jupyter notebook --ip=0.0.0.0 --allow-root --no-browser
