version: "3"
services:
  kaggle-jupyter:
    container_name: 'kaggle-jupyter'
    image: 'okojoalg/kaggle-gpu:v0.1-36'
    runtime: nvidia
    volumes:
      - $PWD:/mount
    working_dir: /mount
    ports:
      - 9876:8080
    command: jupyter notebook --ip=0.0.0.0 --allow-root --no-browser
