version: "2.4"
services:
  kaggle-script:
    container_name: 'kaggle-script'
    image: 'okojoalg/kaggle-gpu:v0.1-36'
    runtime: nvidia
    volumes:
      - $PWD:/mount
    working_dir: /mount
    command: python /mount/run.py
