version: "3"
services:
  kaggle-script:
    container_name: 'kaggle-script'
    image: 'okojoalg/kaggle-gpu:v0.2-36'
    volumes:
      - $PWD:/home
    working_dir: /home
    command: python /home/run.py
