version: "2.4"
services:
  kaggle-script:
    container_name: 'kaggle-script'
    build: ..
    runtime: nvidia
    volumes:
      - $PWD:/mount
    working_dir: /mount
    command: python /mount/run.py
