version: "2.4"
services:
  kaggle-script:
    container_name: 'kaggle-script'
    build: ..
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - $PWD:/home
    working_dir: /home
    command: python /home/run.py
